### ISSUE TITLE
Server to handle get request to page

### ISSUE THREAD

**Issue by jamesongamble** [PiraBoard/studentBoard#4]

**Comment by ateich** [comment]
Does this mean a get request to the server for a user page that returns user data?

**Comment by mikephoran** [comment]
That’s the get request to the index.html for the Admin and User.  I’m guessing we’ll send them to different index.htmls.  One for the users and one for the Admin. 

I’m having trouble tracking which tasks are completed and what tasks are outstanding.  We’re not using Waffle IO, correct?  I looked at the REPO and it looks like none of the server files have been changed, but I also noticed some of the server issues were closed out?

I’m almost done with the server and authentication.  It connects to the database, handles login, signup and the index.html requests.  It also tracks sessions and handles authentication.  I just need to interface it with the database schema.  

It looks like maybe you’ve also done some of this work, Andrew?  

I need to run out to grab lunch, but plan on working some more this evening.  I’m not sure at this point what has already been done and what still needs to be done.   I’m attaching the two files needed to run the server under my formulation.  If you’re working on server stuff Andrew, hopefully you can just crib anything you need from these documents instead of re-inventing the wheel. 

I’ll check in later tonight to see what I can help on.

**Comment by ateich** [comment]
Yeoman did a lot of the work for us, which is why some of the issues are closed despite not having changed the server code since the initial commit.

Send a pull request when you're done, so we can build upon it. Currently, I'm working on the invitation system and have written a "random" url generator to handle it. We still need to add the invite URL to the database, make sure it can only be used once, and allow the user to create their account without having to authenticate. I plan on completing these between today and tomorrow.

**Comment by mikephoran** [comment]
Oh I see.  I didn't realize the default Yeoman was handling sessions and authentication out of the box.  Ok I'll send a pull request tonight when I'm finished.  I spent a lot of my time trimming down the Yeoman to just what we needed.   

Does anyone know the location of the js file that defines the User Model in Mongoose? It's being exported, right? I need to require it in my server file so I can reference it for Authentication purposes.

**Comment by mpint** [comment]
Mike, if you could hop in Google Hangouts it would really help with
communication.

**Comment by ateich** [comment]
server/api/user/user.model.js
